### ISSUE TITLE
Just a question about the setup.

### ISSUE THREAD

**Issue by drot** [alezost/stumpwm-config#1]
Hi, I haven't followed StumpWM progress lately and in your `init.lisp` file I saw the commentary that you compile StumpWM with swank, so I was wondering if you could tell how do you install StumpWM in more detail.

**Comment by alezost** [comment]
Hello!  Sorry for the late answer, I've just noticed this question :-)

I don't install it at all, I just build it from source and run the
resulting `stumpwm` binary.

SBCL is installed using my package manager, and all the lisp dependencies
are installed using [quicklisp](http://www.quicklisp.org/beta/).  Finally,
to have `swank` and `xkeyboard` a part of the stumpwm core file, I made
a single modification in the stumpwm source: I add the following lines to
`load-stumpwm.lisp.in` file (right after `(require 'asdf)`):

``` lisp
(require 'swank)
(require 'xkeyboard)
```

**Comment by drot** [comment]
No worries and thanks for the clarification!
