### ISSUE TITLE
Xlib:get-state 

### ISSUE THREAD

**Issue by commander-trashdin** [alezost/stumpwm-config#2]
It seems it is no longer a thing in xlib.

There are several others.

**Comment by alezost** [comment]
Thank you for letting me know!  I have not updated stumpwm for several months.  Apparently something has changed since then.

Please do not close this issue.  Some day I will update stumpwm and adjust my config accordingly.

**Comment by commander-trashdin** [comment]
I did some more research. It turns out I haven't clx-keyboard installed, and I think those symbols are from there.

That said, I do have several questions about how your config is set up, as this was my go-to trying to setup stump for myself. So if you have time to discuss some details, I'd be glad)

**Comment by alezost** [comment]
You are welcome to ask but I don't promise to answer immediately, so this conversation may last many days :-)

**Comment by alezost** [comment]
I think this issue may be closed now.
@commander-trashdin, let me know if you have any questions.
