### ISSUE TITLE
Using SBCL Libs for Stumpwm with Guix

### ISSUE THREAD

**Issue by jgarte** [alezost/stumpwm-config#3]
Hi, have you tried using various third party sbcl libraries with stumpwm by installing them via guix?

For example, using [threading macros](https://github.com/phoe/binding-arrows).

`guix install sbcl-binding-arrows`

**Comment by alezost** [comment]
Hello,
No I don't install lisp packages via guix.

**Comment by jgarte** [comment]
How do you install them usually?

**Comment by alezost** [comment]
I install all Lisp libraries using [QuickLisp](https://www.quicklisp.org/beta/)

**Comment by jgarte** [comment]
@alezost I'd be curious for you to try out the following and let me know what you think if you have the time:

https://git.sr.ht/~whereiseveryone/guixrus-scripts
https://git.sr.ht/~charje/cl-guix-utils

It basically gives you the quicklisp experience but with Guix.

**Comment by ebrasca** [comment]
I like to ask how do you start stumpwm in your GuixSD.

Thank you!

**Comment by jgarte** [comment]
I don't because I use rde [with sway](https://toys.whereis.みんな/symbols?search=feature-sway) now, btw ;()

https://trop.in/rde
https://git.sr.ht/~whereiseveryone/confetti

happy hacking
--
jgart

TODO: message GitHub and tell them they have a bug with editing markdown in browser after sending to issues from email.
